import { useState } from 'react'
import { Download } from 'lucide-react'
import { getTotalStats, formatNumber, buildLanguageData } from '../utils/formatters'

export default function PDFExport({ user, repos }) {
  const [loading, setLoading] = useState(false)

  async function exportPDF() {
    setLoading(true)
    const stats = getTotalStats(repos)
    const langs = buildLanguageData(repos).slice(0, 5).map(l => l.name).join(', ')

    const html = `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: Arial, sans-serif; max-width: 700px; margin: 40px auto; color: #111; }
  .header { display: flex; align-items: center; gap: 20px; border-bottom: 2px solid #e5e7eb; padding-bottom: 20px; margin-bottom: 24px; }
  img { width: 80px; height: 80px; border-radius: 50%; }
  h1 { margin: 0; font-size: 24px; } h2 { margin: 0; font-size: 14px; color: #6b7280; }
  .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 20px 0; }
  .stat { background: #f9fafb; border-radius: 10px; padding: 14px; text-align: center; }
  .stat-val { font-size: 22px; font-weight: bold; color: #111; }
  .stat-label { font-size: 11px; color: #6b7280; margin-top: 4px; }
  .section { margin-top: 24px; }
  .section h3 { font-size: 14px; font-weight: 600; margin-bottom: 12px; color: #374151; border-left: 3px solid #6366f1; padding-left: 10px; }
  .repo { padding: 10px 0; border-bottom: 1px solid #f3f4f6; display: flex; justify-content: space-between; }
  .repo-name { font-weight: 500; font-size: 13px; color: #1d4ed8; }
  .repo-meta { font-size: 11px; color: #9ca3af; }
  .badge { display: inline-block; background: #ede9fe; color: #5b21b6; border-radius: 999px; padding: 2px 8px; font-size: 11px; margin: 2px; }
  .footer { margin-top: 32px; font-size: 11px; color: #9ca3af; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 16px; }
</style>
</head>
<body>
<div class="header">
  <img src="${user.avatar_url}" alt="${user.login}" />
  <div>
    <h1>${user.name || user.login}</h1>
    <h2>@${user.login}</h2>
    ${user.bio ? `<p style="font-size:13px;color:#4b5563;margin:6px 0 0">${user.bio}</p>` : ''}
    ${user.location ? `<p style="font-size:12px;color:#6b7280;margin:4px 0 0">📍 ${user.location}</p>` : ''}
  </div>
</div>

<div class="stats">
  <div class="stat"><div class="stat-val">${formatNumber(user.followers)}</div><div class="stat-label">Followers</div></div>
  <div class="stat"><div class="stat-val">${formatNumber(user.public_repos)}</div><div class="stat-label">Repos</div></div>
  <div class="stat"><div class="stat-val">${formatNumber(stats.totalStars)}</div><div class="stat-label">Total Stars</div></div>
  <div class="stat"><div class="stat-val">${formatNumber(stats.totalForks)}</div><div class="stat-label">Total Forks</div></div>
</div>

<div class="section">
  <h3>Top Languages</h3>
  <div>${langs.split(', ').map(l => `<span class="badge">${l}</span>`).join('')}</div>
</div>

<div class="section">
  <h3>Top Repositories</h3>
  ${[...repos].sort((a,b) => b.stargazers_count - a.stargazers_count).slice(0,8).map(r => `
    <div class="repo">
      <div>
        <div class="repo-name">${r.name}</div>
        ${r.description ? `<div class="repo-meta">${r.description.slice(0,80)}</div>` : ''}
      </div>
      <div class="repo-meta" style="text-align:right">⭐ ${r.stargazers_count}<br/>🍴 ${r.forks_count}</div>
    </div>
  `).join('')}
</div>

<div class="footer">Generated by GitHub Profile Viewer • ${new Date().toLocaleDateString()}</div>
</body>
</html>`

    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const win = window.open(url, '_blank')
    if (win) {
      win.onload = () => {
        win.print()
        URL.revokeObjectURL(url)
      }
    }
    setLoading(false)
  }

  return (
    <button
      onClick={exportPDF}
      disabled={loading}
      className="flex items-center gap-2 w-full justify-center py-2.5 rounded-xl border border-gray-200 dark:border-gray-700 text-sm text-gray-600 dark:text-gray-400 hover:bg-gray-50 dark:hover:bg-gray-800 transition disabled:opacity-50"
    >
      <Download size={15} />
      {loading ? 'Preparing...' : 'Export as PDF'}
    </button>
  )
}
